#! /usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright © 2016 Clay L. McLeod <clay.l.mcleod@gmail.com>
#
# Distributed under terms of the MIT license.

from __future__ import print_function

import re
from celcius.cmds import crontab

length_of_status_str = 60

def format_status_for_cmd(cmd):
    match = None
    match = re.search(r'CJOBID=\'\w+\'', cmd)
    if match:
        jobid = re.search(r'\d+', match.group())
        if jobid:
            jobstr = "[Job {}]".format(jobid.group())
            cutoff_str = "MAILTO=''"
            cutoff_index = cmd.index(cutoff_str) + len(cutoff_str)
            modified_str = cmd[cutoff_index:cutoff_index+length_of_status_str]
            return "{} {}...".format(jobstr.rjust(12, ' '), modified_str)

commands = crontab.get_all_celcius_commands()
for cmd in commands:
    print(format_status_for_cmd(cmd))
