#! /usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright © 2016 Clay L. McLeod <clay.l.mcleod@gmail.com>
#
# Distributed under terms of the MIT license.

from __future__ import print_function

import os, sys, json
from celcius import celciusmenu, file_utils

home_path = '~'
env_home_path = os.environ.get('HOME')
if env_home_path != None:
    home_path = env_home_path

dot_celcius_folder = os.path.join(home_path, '.celcius')

if not os.path.isdir(dot_celcius_folder):
    print('Initializing celcius...')
    os.makedirs(dot_celcius_folder)

    print('Configuring system...')
    retrieve_command = ''

    if file_utils.command_exists('curl'):
        retrieve_command = 'curl'
    elif file_utils.command_exists('wget'):
        retrieve_command = 'wget'
    else:
        print("ERROR: must have curl or wget installed and on your $PATH!!!")
        sys.exit(1)

    configuration = {
        'retrieve_command': retrieve_command
    }


    config_path = os.path.join(dot_celcius_folder, 'config.json')
    with open(config_path, 'w') as f:
        json.dump(configuration, f, sort_keys=True, indent=4, separators=(',', ': '))

    raw_input('Press [ENTER] to continue...')
