#! /usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright © 2016 Clay L. McLeod <clay.l.mcleod@gmail.com>
#
# Distributed under terms of the MIT license.

from __future__ import print_function

import os, sys, json
from celcius import celciusmenu, file_utils

home_path = '~'
env_home_path = os.environ.get('HOME')
if env_home_path != None:
    home_path = env_home_path

dot_celcius_folder = os.path.join(home_path, '.celcius')

if not os.path.isdir(dot_celcius_folder):
    print("Must first run celcius-init!")
    sys.exit(1)

celciusmenu.main()
